[build]
  publish   = "."
  functions = "netlify/functions"
  command   = "npm install"

[[redirects]]
  from   = "/"
  to     = "/Index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
